version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=nerfcfm.settings

  redis:
    image: redis:latest

  celery:
    build: .
    command: celery -A nerfcfm.celery worker -l INFO
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=nerfcfm.settings

