# Generated by Django 4.2.7 on 2023-11-30 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nerfcfm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nerf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('long_name', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='nerfmodel',
            name='nerf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nerfcfm.nerf'),
        ),
    ]
